---
title: "ML application"
author: "Federico Cortese"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Packages

```{r}
require(MASS)
```


## Data loading

```{r}
load("df_train.Rdata")
summary(df_train)
barplot(table(df_train$id_participant))
max(table(df_train$id_participant))
which.max(table(df_train$id_participant))

```

```{r}
df_xesh029=df_train[df_train$id_participant=='xesh029',]
```

# Proportional odds ratio

Clean dataset

```{r}
#load("df_train.Rdata")
names(df_train)
```

Response variable: thermal preference

```{r}
y=df_train$q_thermal_preference
summary(y)
barplot(table(y)/length(y),col=rainbow(length(unique(y))))
```

Explanatory variables

```{r}
X=df_train[c("air_temp","rainfall","relative_humidity","wind_speed","wind_dir",
             "ts_stand_time","ts_step_count","ts_walking_distance","ts_heart_rate",
             "q_location","q_location_office","q_location_transport",
             "Green.View.Mean","Sky.View.Mean","Building.View.Mean","Road.View.Mean",
             "q_activity_category_alone","q_activity_category_group",
             #cross-modal effects
             "q_earphones","q_noise_kind","q_noise_nearby")]
summary(X)
```


